# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cosmicentropy/projects/data-structs-and-algos

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cosmicentropy/projects/data-structs-and-algos

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cosmicentropy/projects/data-structs-and-algos/CMakeFiles /home/cosmicentropy/projects/data-structs-and-algos//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cosmicentropy/projects/data-structs-and-algos/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named check-expression-balance.o

# Build rule for target.
check-expression-balance.o: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 check-expression-balance.o
.PHONY : check-expression-balance.o

# fast build rule for target.
check-expression-balance.o/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check-expression-balance.o.dir/build.make CMakeFiles/check-expression-balance.o.dir/build
.PHONY : check-expression-balance.o/fast

#=============================================================================
# Target rules for targets named evaluate-infix.o

# Build rule for target.
evaluate-infix.o: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 evaluate-infix.o
.PHONY : evaluate-infix.o

# fast build rule for target.
evaluate-infix.o/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/evaluate-infix.o.dir/build.make CMakeFiles/evaluate-infix.o.dir/build
.PHONY : evaluate-infix.o/fast

#=============================================================================
# Target rules for targets named prefix-to-postfix.o

# Build rule for target.
prefix-to-postfix.o: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 prefix-to-postfix.o
.PHONY : prefix-to-postfix.o

# fast build rule for target.
prefix-to-postfix.o/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prefix-to-postfix.o.dir/build.make CMakeFiles/prefix-to-postfix.o.dir/build
.PHONY : prefix-to-postfix.o/fast

#=============================================================================
# Target rules for targets named stack-sequence-validation.o

# Build rule for target.
stack-sequence-validation.o: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stack-sequence-validation.o
.PHONY : stack-sequence-validation.o

# fast build rule for target.
stack-sequence-validation.o/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stack-sequence-validation.o.dir/build.make CMakeFiles/stack-sequence-validation.o.dir/build
.PHONY : stack-sequence-validation.o/fast

#=============================================================================
# Target rules for targets named decimal-number-calc.o

# Build rule for target.
decimal-number-calc.o: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 decimal-number-calc.o
.PHONY : decimal-number-calc.o

# fast build rule for target.
decimal-number-calc.o/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decimal-number-calc.o.dir/build.make CMakeFiles/decimal-number-calc.o.dir/build
.PHONY : decimal-number-calc.o/fast

#=============================================================================
# Target rules for targets named binary-tree-test.o

# Build rule for target.
binary-tree-test.o: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 binary-tree-test.o
.PHONY : binary-tree-test.o

# fast build rule for target.
binary-tree-test.o/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary-tree-test.o.dir/build.make CMakeFiles/binary-tree-test.o.dir/build
.PHONY : binary-tree-test.o/fast

#=============================================================================
# Target rules for targets named linked-list-test.o

# Build rule for target.
linked-list-test.o: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 linked-list-test.o
.PHONY : linked-list-test.o

# fast build rule for target.
linked-list-test.o/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linked-list-test.o.dir/build.make CMakeFiles/linked-list-test.o.dir/build
.PHONY : linked-list-test.o/fast

#=============================================================================
# Target rules for targets named cd-linked-list-test.o

# Build rule for target.
cd-linked-list-test.o: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cd-linked-list-test.o
.PHONY : cd-linked-list-test.o

# fast build rule for target.
cd-linked-list-test.o/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cd-linked-list-test.o.dir/build.make CMakeFiles/cd-linked-list-test.o.dir/build
.PHONY : cd-linked-list-test.o/fast

#=============================================================================
# Target rules for targets named max-heap-test.o

# Build rule for target.
max-heap-test.o: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 max-heap-test.o
.PHONY : max-heap-test.o

# fast build rule for target.
max-heap-test.o/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/max-heap-test.o.dir/build.make CMakeFiles/max-heap-test.o.dir/build
.PHONY : max-heap-test.o/fast

#=============================================================================
# Target rules for targets named min-heap-test.o

# Build rule for target.
min-heap-test.o: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 min-heap-test.o
.PHONY : min-heap-test.o

# fast build rule for target.
min-heap-test.o/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min-heap-test.o.dir/build.make CMakeFiles/min-heap-test.o.dir/build
.PHONY : min-heap-test.o/fast

#=============================================================================
# Target rules for targets named kmp-pattern-matching.o

# Build rule for target.
kmp-pattern-matching.o: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kmp-pattern-matching.o
.PHONY : kmp-pattern-matching.o

# fast build rule for target.
kmp-pattern-matching.o/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kmp-pattern-matching.o.dir/build.make CMakeFiles/kmp-pattern-matching.o.dir/build
.PHONY : kmp-pattern-matching.o/fast

#=============================================================================
# Target rules for targets named magic-square.o

# Build rule for target.
magic-square.o: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 magic-square.o
.PHONY : magic-square.o

# fast build rule for target.
magic-square.o/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magic-square.o.dir/build.make CMakeFiles/magic-square.o.dir/build
.PHONY : magic-square.o/fast

#=============================================================================
# Target rules for targets named calculator.o

# Build rule for target.
calculator.o: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 calculator.o
.PHONY : calculator.o

# fast build rule for target.
calculator.o/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.o.dir/build.make CMakeFiles/calculator.o.dir/build
.PHONY : calculator.o/fast

#=============================================================================
# Target rules for targets named avl-tree-test.o

# Build rule for target.
avl-tree-test.o: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 avl-tree-test.o
.PHONY : avl-tree-test.o

# fast build rule for target.
avl-tree-test.o/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avl-tree-test.o.dir/build.make CMakeFiles/avl-tree-test.o.dir/build
.PHONY : avl-tree-test.o/fast

#=============================================================================
# Target rules for targets named strassen-matrix-mult.o

# Build rule for target.
strassen-matrix-mult.o: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 strassen-matrix-mult.o
.PHONY : strassen-matrix-mult.o

# fast build rule for target.
strassen-matrix-mult.o/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strassen-matrix-mult.o.dir/build.make CMakeFiles/strassen-matrix-mult.o.dir/build
.PHONY : strassen-matrix-mult.o/fast

#=============================================================================
# Target rules for targets named binary-search.o

# Build rule for target.
binary-search.o: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 binary-search.o
.PHONY : binary-search.o

# fast build rule for target.
binary-search.o/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary-search.o.dir/build.make CMakeFiles/binary-search.o.dir/build
.PHONY : binary-search.o/fast

#=============================================================================
# Target rules for targets named recursive-binary-search.o

# Build rule for target.
recursive-binary-search.o: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 recursive-binary-search.o
.PHONY : recursive-binary-search.o

# fast build rule for target.
recursive-binary-search.o/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/recursive-binary-search.o.dir/build.make CMakeFiles/recursive-binary-search.o.dir/build
.PHONY : recursive-binary-search.o/fast

#=============================================================================
# Target rules for targets named linear-search.o

# Build rule for target.
linear-search.o: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 linear-search.o
.PHONY : linear-search.o

# fast build rule for target.
linear-search.o/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linear-search.o.dir/build.make CMakeFiles/linear-search.o.dir/build
.PHONY : linear-search.o/fast

#=============================================================================
# Target rules for targets named merge-sort.o

# Build rule for target.
merge-sort.o: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 merge-sort.o
.PHONY : merge-sort.o

# fast build rule for target.
merge-sort.o/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/merge-sort.o.dir/build.make CMakeFiles/merge-sort.o.dir/build
.PHONY : merge-sort.o/fast

#=============================================================================
# Target rules for targets named bubble-sort.o

# Build rule for target.
bubble-sort.o: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bubble-sort.o
.PHONY : bubble-sort.o

# fast build rule for target.
bubble-sort.o/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bubble-sort.o.dir/build.make CMakeFiles/bubble-sort.o.dir/build
.PHONY : bubble-sort.o/fast

#=============================================================================
# Target rules for targets named quick-sort.o

# Build rule for target.
quick-sort.o: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quick-sort.o
.PHONY : quick-sort.o

# fast build rule for target.
quick-sort.o/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quick-sort.o.dir/build.make CMakeFiles/quick-sort.o.dir/build
.PHONY : quick-sort.o/fast

#=============================================================================
# Target rules for targets named selection-sort.o

# Build rule for target.
selection-sort.o: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 selection-sort.o
.PHONY : selection-sort.o

# fast build rule for target.
selection-sort.o/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/selection-sort.o.dir/build.make CMakeFiles/selection-sort.o.dir/build
.PHONY : selection-sort.o/fast

src/AVLTree/AVLTree.o: src/AVLTree/AVLTree.cpp.o
.PHONY : src/AVLTree/AVLTree.o

# target to build an object file
src/AVLTree/AVLTree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avl-tree-test.o.dir/build.make CMakeFiles/avl-tree-test.o.dir/src/AVLTree/AVLTree.cpp.o
.PHONY : src/AVLTree/AVLTree.cpp.o

src/AVLTree/AVLTree.i: src/AVLTree/AVLTree.cpp.i
.PHONY : src/AVLTree/AVLTree.i

# target to preprocess a source file
src/AVLTree/AVLTree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avl-tree-test.o.dir/build.make CMakeFiles/avl-tree-test.o.dir/src/AVLTree/AVLTree.cpp.i
.PHONY : src/AVLTree/AVLTree.cpp.i

src/AVLTree/AVLTree.s: src/AVLTree/AVLTree.cpp.s
.PHONY : src/AVLTree/AVLTree.s

# target to generate assembly for a file
src/AVLTree/AVLTree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avl-tree-test.o.dir/build.make CMakeFiles/avl-tree-test.o.dir/src/AVLTree/AVLTree.cpp.s
.PHONY : src/AVLTree/AVLTree.cpp.s

src/BinaryTree/BinaryTree.o: src/BinaryTree/BinaryTree.cpp.o
.PHONY : src/BinaryTree/BinaryTree.o

# target to build an object file
src/BinaryTree/BinaryTree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary-tree-test.o.dir/build.make CMakeFiles/binary-tree-test.o.dir/src/BinaryTree/BinaryTree.cpp.o
.PHONY : src/BinaryTree/BinaryTree.cpp.o

src/BinaryTree/BinaryTree.i: src/BinaryTree/BinaryTree.cpp.i
.PHONY : src/BinaryTree/BinaryTree.i

# target to preprocess a source file
src/BinaryTree/BinaryTree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary-tree-test.o.dir/build.make CMakeFiles/binary-tree-test.o.dir/src/BinaryTree/BinaryTree.cpp.i
.PHONY : src/BinaryTree/BinaryTree.cpp.i

src/BinaryTree/BinaryTree.s: src/BinaryTree/BinaryTree.cpp.s
.PHONY : src/BinaryTree/BinaryTree.s

# target to generate assembly for a file
src/BinaryTree/BinaryTree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary-tree-test.o.dir/build.make CMakeFiles/binary-tree-test.o.dir/src/BinaryTree/BinaryTree.cpp.s
.PHONY : src/BinaryTree/BinaryTree.cpp.s

src/CDLinkedList/CDLinkedList.o: src/CDLinkedList/CDLinkedList.cpp.o
.PHONY : src/CDLinkedList/CDLinkedList.o

# target to build an object file
src/CDLinkedList/CDLinkedList.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cd-linked-list-test.o.dir/build.make CMakeFiles/cd-linked-list-test.o.dir/src/CDLinkedList/CDLinkedList.cpp.o
.PHONY : src/CDLinkedList/CDLinkedList.cpp.o

src/CDLinkedList/CDLinkedList.i: src/CDLinkedList/CDLinkedList.cpp.i
.PHONY : src/CDLinkedList/CDLinkedList.i

# target to preprocess a source file
src/CDLinkedList/CDLinkedList.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cd-linked-list-test.o.dir/build.make CMakeFiles/cd-linked-list-test.o.dir/src/CDLinkedList/CDLinkedList.cpp.i
.PHONY : src/CDLinkedList/CDLinkedList.cpp.i

src/CDLinkedList/CDLinkedList.s: src/CDLinkedList/CDLinkedList.cpp.s
.PHONY : src/CDLinkedList/CDLinkedList.s

# target to generate assembly for a file
src/CDLinkedList/CDLinkedList.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cd-linked-list-test.o.dir/build.make CMakeFiles/cd-linked-list-test.o.dir/src/CDLinkedList/CDLinkedList.cpp.s
.PHONY : src/CDLinkedList/CDLinkedList.cpp.s

src/DecimalNumber/DecimalNumber.o: src/DecimalNumber/DecimalNumber.cpp.o
.PHONY : src/DecimalNumber/DecimalNumber.o

# target to build an object file
src/DecimalNumber/DecimalNumber.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decimal-number-calc.o.dir/build.make CMakeFiles/decimal-number-calc.o.dir/src/DecimalNumber/DecimalNumber.cpp.o
.PHONY : src/DecimalNumber/DecimalNumber.cpp.o

src/DecimalNumber/DecimalNumber.i: src/DecimalNumber/DecimalNumber.cpp.i
.PHONY : src/DecimalNumber/DecimalNumber.i

# target to preprocess a source file
src/DecimalNumber/DecimalNumber.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decimal-number-calc.o.dir/build.make CMakeFiles/decimal-number-calc.o.dir/src/DecimalNumber/DecimalNumber.cpp.i
.PHONY : src/DecimalNumber/DecimalNumber.cpp.i

src/DecimalNumber/DecimalNumber.s: src/DecimalNumber/DecimalNumber.cpp.s
.PHONY : src/DecimalNumber/DecimalNumber.s

# target to generate assembly for a file
src/DecimalNumber/DecimalNumber.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decimal-number-calc.o.dir/build.make CMakeFiles/decimal-number-calc.o.dir/src/DecimalNumber/DecimalNumber.cpp.s
.PHONY : src/DecimalNumber/DecimalNumber.cpp.s

src/Heap/MaxHeap.o: src/Heap/MaxHeap.cpp.o
.PHONY : src/Heap/MaxHeap.o

# target to build an object file
src/Heap/MaxHeap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/max-heap-test.o.dir/build.make CMakeFiles/max-heap-test.o.dir/src/Heap/MaxHeap.cpp.o
.PHONY : src/Heap/MaxHeap.cpp.o

src/Heap/MaxHeap.i: src/Heap/MaxHeap.cpp.i
.PHONY : src/Heap/MaxHeap.i

# target to preprocess a source file
src/Heap/MaxHeap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/max-heap-test.o.dir/build.make CMakeFiles/max-heap-test.o.dir/src/Heap/MaxHeap.cpp.i
.PHONY : src/Heap/MaxHeap.cpp.i

src/Heap/MaxHeap.s: src/Heap/MaxHeap.cpp.s
.PHONY : src/Heap/MaxHeap.s

# target to generate assembly for a file
src/Heap/MaxHeap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/max-heap-test.o.dir/build.make CMakeFiles/max-heap-test.o.dir/src/Heap/MaxHeap.cpp.s
.PHONY : src/Heap/MaxHeap.cpp.s

src/Heap/MinHeap.o: src/Heap/MinHeap.cpp.o
.PHONY : src/Heap/MinHeap.o

# target to build an object file
src/Heap/MinHeap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min-heap-test.o.dir/build.make CMakeFiles/min-heap-test.o.dir/src/Heap/MinHeap.cpp.o
.PHONY : src/Heap/MinHeap.cpp.o

src/Heap/MinHeap.i: src/Heap/MinHeap.cpp.i
.PHONY : src/Heap/MinHeap.i

# target to preprocess a source file
src/Heap/MinHeap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min-heap-test.o.dir/build.make CMakeFiles/min-heap-test.o.dir/src/Heap/MinHeap.cpp.i
.PHONY : src/Heap/MinHeap.cpp.i

src/Heap/MinHeap.s: src/Heap/MinHeap.cpp.s
.PHONY : src/Heap/MinHeap.s

# target to generate assembly for a file
src/Heap/MinHeap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min-heap-test.o.dir/build.make CMakeFiles/min-heap-test.o.dir/src/Heap/MinHeap.cpp.s
.PHONY : src/Heap/MinHeap.cpp.s

src/LinkedList/LinkedList.o: src/LinkedList/LinkedList.cpp.o
.PHONY : src/LinkedList/LinkedList.o

# target to build an object file
src/LinkedList/LinkedList.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linked-list-test.o.dir/build.make CMakeFiles/linked-list-test.o.dir/src/LinkedList/LinkedList.cpp.o
.PHONY : src/LinkedList/LinkedList.cpp.o

src/LinkedList/LinkedList.i: src/LinkedList/LinkedList.cpp.i
.PHONY : src/LinkedList/LinkedList.i

# target to preprocess a source file
src/LinkedList/LinkedList.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linked-list-test.o.dir/build.make CMakeFiles/linked-list-test.o.dir/src/LinkedList/LinkedList.cpp.i
.PHONY : src/LinkedList/LinkedList.cpp.i

src/LinkedList/LinkedList.s: src/LinkedList/LinkedList.cpp.s
.PHONY : src/LinkedList/LinkedList.s

# target to generate assembly for a file
src/LinkedList/LinkedList.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linked-list-test.o.dir/build.make CMakeFiles/linked-list-test.o.dir/src/LinkedList/LinkedList.cpp.s
.PHONY : src/LinkedList/LinkedList.cpp.s

src/Queue/Queue.o: src/Queue/Queue.cpp.o
.PHONY : src/Queue/Queue.o

# target to build an object file
src/Queue/Queue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary-tree-test.o.dir/build.make CMakeFiles/binary-tree-test.o.dir/src/Queue/Queue.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.o.dir/build.make CMakeFiles/calculator.o.dir/src/Queue/Queue.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avl-tree-test.o.dir/build.make CMakeFiles/avl-tree-test.o.dir/src/Queue/Queue.cpp.o
.PHONY : src/Queue/Queue.cpp.o

src/Queue/Queue.i: src/Queue/Queue.cpp.i
.PHONY : src/Queue/Queue.i

# target to preprocess a source file
src/Queue/Queue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary-tree-test.o.dir/build.make CMakeFiles/binary-tree-test.o.dir/src/Queue/Queue.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.o.dir/build.make CMakeFiles/calculator.o.dir/src/Queue/Queue.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avl-tree-test.o.dir/build.make CMakeFiles/avl-tree-test.o.dir/src/Queue/Queue.cpp.i
.PHONY : src/Queue/Queue.cpp.i

src/Queue/Queue.s: src/Queue/Queue.cpp.s
.PHONY : src/Queue/Queue.s

# target to generate assembly for a file
src/Queue/Queue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary-tree-test.o.dir/build.make CMakeFiles/binary-tree-test.o.dir/src/Queue/Queue.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.o.dir/build.make CMakeFiles/calculator.o.dir/src/Queue/Queue.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avl-tree-test.o.dir/build.make CMakeFiles/avl-tree-test.o.dir/src/Queue/Queue.cpp.s
.PHONY : src/Queue/Queue.cpp.s

src/Stack/Stack.o: src/Stack/Stack.cpp.o
.PHONY : src/Stack/Stack.o

# target to build an object file
src/Stack/Stack.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check-expression-balance.o.dir/build.make CMakeFiles/check-expression-balance.o.dir/src/Stack/Stack.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/evaluate-infix.o.dir/build.make CMakeFiles/evaluate-infix.o.dir/src/Stack/Stack.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prefix-to-postfix.o.dir/build.make CMakeFiles/prefix-to-postfix.o.dir/src/Stack/Stack.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stack-sequence-validation.o.dir/build.make CMakeFiles/stack-sequence-validation.o.dir/src/Stack/Stack.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.o.dir/build.make CMakeFiles/calculator.o.dir/src/Stack/Stack.cpp.o
.PHONY : src/Stack/Stack.cpp.o

src/Stack/Stack.i: src/Stack/Stack.cpp.i
.PHONY : src/Stack/Stack.i

# target to preprocess a source file
src/Stack/Stack.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check-expression-balance.o.dir/build.make CMakeFiles/check-expression-balance.o.dir/src/Stack/Stack.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/evaluate-infix.o.dir/build.make CMakeFiles/evaluate-infix.o.dir/src/Stack/Stack.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prefix-to-postfix.o.dir/build.make CMakeFiles/prefix-to-postfix.o.dir/src/Stack/Stack.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stack-sequence-validation.o.dir/build.make CMakeFiles/stack-sequence-validation.o.dir/src/Stack/Stack.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.o.dir/build.make CMakeFiles/calculator.o.dir/src/Stack/Stack.cpp.i
.PHONY : src/Stack/Stack.cpp.i

src/Stack/Stack.s: src/Stack/Stack.cpp.s
.PHONY : src/Stack/Stack.s

# target to generate assembly for a file
src/Stack/Stack.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check-expression-balance.o.dir/build.make CMakeFiles/check-expression-balance.o.dir/src/Stack/Stack.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/evaluate-infix.o.dir/build.make CMakeFiles/evaluate-infix.o.dir/src/Stack/Stack.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prefix-to-postfix.o.dir/build.make CMakeFiles/prefix-to-postfix.o.dir/src/Stack/Stack.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stack-sequence-validation.o.dir/build.make CMakeFiles/stack-sequence-validation.o.dir/src/Stack/Stack.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.o.dir/build.make CMakeFiles/calculator.o.dir/src/Stack/Stack.cpp.s
.PHONY : src/Stack/Stack.cpp.s

src/binary-tree-test.o: src/binary-tree-test.cpp.o
.PHONY : src/binary-tree-test.o

# target to build an object file
src/binary-tree-test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary-tree-test.o.dir/build.make CMakeFiles/binary-tree-test.o.dir/src/binary-tree-test.cpp.o
.PHONY : src/binary-tree-test.cpp.o

src/binary-tree-test.i: src/binary-tree-test.cpp.i
.PHONY : src/binary-tree-test.i

# target to preprocess a source file
src/binary-tree-test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary-tree-test.o.dir/build.make CMakeFiles/binary-tree-test.o.dir/src/binary-tree-test.cpp.i
.PHONY : src/binary-tree-test.cpp.i

src/binary-tree-test.s: src/binary-tree-test.cpp.s
.PHONY : src/binary-tree-test.s

# target to generate assembly for a file
src/binary-tree-test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary-tree-test.o.dir/build.make CMakeFiles/binary-tree-test.o.dir/src/binary-tree-test.cpp.s
.PHONY : src/binary-tree-test.cpp.s

src/cd-linked-list-test.o: src/cd-linked-list-test.cpp.o
.PHONY : src/cd-linked-list-test.o

# target to build an object file
src/cd-linked-list-test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cd-linked-list-test.o.dir/build.make CMakeFiles/cd-linked-list-test.o.dir/src/cd-linked-list-test.cpp.o
.PHONY : src/cd-linked-list-test.cpp.o

src/cd-linked-list-test.i: src/cd-linked-list-test.cpp.i
.PHONY : src/cd-linked-list-test.i

# target to preprocess a source file
src/cd-linked-list-test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cd-linked-list-test.o.dir/build.make CMakeFiles/cd-linked-list-test.o.dir/src/cd-linked-list-test.cpp.i
.PHONY : src/cd-linked-list-test.cpp.i

src/cd-linked-list-test.s: src/cd-linked-list-test.cpp.s
.PHONY : src/cd-linked-list-test.s

# target to generate assembly for a file
src/cd-linked-list-test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cd-linked-list-test.o.dir/build.make CMakeFiles/cd-linked-list-test.o.dir/src/cd-linked-list-test.cpp.s
.PHONY : src/cd-linked-list-test.cpp.s

src/check-expression-balance.o: src/check-expression-balance.cpp.o
.PHONY : src/check-expression-balance.o

# target to build an object file
src/check-expression-balance.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check-expression-balance.o.dir/build.make CMakeFiles/check-expression-balance.o.dir/src/check-expression-balance.cpp.o
.PHONY : src/check-expression-balance.cpp.o

src/check-expression-balance.i: src/check-expression-balance.cpp.i
.PHONY : src/check-expression-balance.i

# target to preprocess a source file
src/check-expression-balance.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check-expression-balance.o.dir/build.make CMakeFiles/check-expression-balance.o.dir/src/check-expression-balance.cpp.i
.PHONY : src/check-expression-balance.cpp.i

src/check-expression-balance.s: src/check-expression-balance.cpp.s
.PHONY : src/check-expression-balance.s

# target to generate assembly for a file
src/check-expression-balance.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check-expression-balance.o.dir/build.make CMakeFiles/check-expression-balance.o.dir/src/check-expression-balance.cpp.s
.PHONY : src/check-expression-balance.cpp.s

src/decimal-number-calc.o: src/decimal-number-calc.cpp.o
.PHONY : src/decimal-number-calc.o

# target to build an object file
src/decimal-number-calc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decimal-number-calc.o.dir/build.make CMakeFiles/decimal-number-calc.o.dir/src/decimal-number-calc.cpp.o
.PHONY : src/decimal-number-calc.cpp.o

src/decimal-number-calc.i: src/decimal-number-calc.cpp.i
.PHONY : src/decimal-number-calc.i

# target to preprocess a source file
src/decimal-number-calc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decimal-number-calc.o.dir/build.make CMakeFiles/decimal-number-calc.o.dir/src/decimal-number-calc.cpp.i
.PHONY : src/decimal-number-calc.cpp.i

src/decimal-number-calc.s: src/decimal-number-calc.cpp.s
.PHONY : src/decimal-number-calc.s

# target to generate assembly for a file
src/decimal-number-calc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/decimal-number-calc.o.dir/build.make CMakeFiles/decimal-number-calc.o.dir/src/decimal-number-calc.cpp.s
.PHONY : src/decimal-number-calc.cpp.s

src/evaluate-infix.o: src/evaluate-infix.cpp.o
.PHONY : src/evaluate-infix.o

# target to build an object file
src/evaluate-infix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/evaluate-infix.o.dir/build.make CMakeFiles/evaluate-infix.o.dir/src/evaluate-infix.cpp.o
.PHONY : src/evaluate-infix.cpp.o

src/evaluate-infix.i: src/evaluate-infix.cpp.i
.PHONY : src/evaluate-infix.i

# target to preprocess a source file
src/evaluate-infix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/evaluate-infix.o.dir/build.make CMakeFiles/evaluate-infix.o.dir/src/evaluate-infix.cpp.i
.PHONY : src/evaluate-infix.cpp.i

src/evaluate-infix.s: src/evaluate-infix.cpp.s
.PHONY : src/evaluate-infix.s

# target to generate assembly for a file
src/evaluate-infix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/evaluate-infix.o.dir/build.make CMakeFiles/evaluate-infix.o.dir/src/evaluate-infix.cpp.s
.PHONY : src/evaluate-infix.cpp.s

src/kmp-pattern-matching.o: src/kmp-pattern-matching.cpp.o
.PHONY : src/kmp-pattern-matching.o

# target to build an object file
src/kmp-pattern-matching.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kmp-pattern-matching.o.dir/build.make CMakeFiles/kmp-pattern-matching.o.dir/src/kmp-pattern-matching.cpp.o
.PHONY : src/kmp-pattern-matching.cpp.o

src/kmp-pattern-matching.i: src/kmp-pattern-matching.cpp.i
.PHONY : src/kmp-pattern-matching.i

# target to preprocess a source file
src/kmp-pattern-matching.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kmp-pattern-matching.o.dir/build.make CMakeFiles/kmp-pattern-matching.o.dir/src/kmp-pattern-matching.cpp.i
.PHONY : src/kmp-pattern-matching.cpp.i

src/kmp-pattern-matching.s: src/kmp-pattern-matching.cpp.s
.PHONY : src/kmp-pattern-matching.s

# target to generate assembly for a file
src/kmp-pattern-matching.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kmp-pattern-matching.o.dir/build.make CMakeFiles/kmp-pattern-matching.o.dir/src/kmp-pattern-matching.cpp.s
.PHONY : src/kmp-pattern-matching.cpp.s

src/linked-list-test.o: src/linked-list-test.cpp.o
.PHONY : src/linked-list-test.o

# target to build an object file
src/linked-list-test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linked-list-test.o.dir/build.make CMakeFiles/linked-list-test.o.dir/src/linked-list-test.cpp.o
.PHONY : src/linked-list-test.cpp.o

src/linked-list-test.i: src/linked-list-test.cpp.i
.PHONY : src/linked-list-test.i

# target to preprocess a source file
src/linked-list-test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linked-list-test.o.dir/build.make CMakeFiles/linked-list-test.o.dir/src/linked-list-test.cpp.i
.PHONY : src/linked-list-test.cpp.i

src/linked-list-test.s: src/linked-list-test.cpp.s
.PHONY : src/linked-list-test.s

# target to generate assembly for a file
src/linked-list-test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linked-list-test.o.dir/build.make CMakeFiles/linked-list-test.o.dir/src/linked-list-test.cpp.s
.PHONY : src/linked-list-test.cpp.s

src/main-apps/avl-tree-test.o: src/main-apps/avl-tree-test.cpp.o
.PHONY : src/main-apps/avl-tree-test.o

# target to build an object file
src/main-apps/avl-tree-test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avl-tree-test.o.dir/build.make CMakeFiles/avl-tree-test.o.dir/src/main-apps/avl-tree-test.cpp.o
.PHONY : src/main-apps/avl-tree-test.cpp.o

src/main-apps/avl-tree-test.i: src/main-apps/avl-tree-test.cpp.i
.PHONY : src/main-apps/avl-tree-test.i

# target to preprocess a source file
src/main-apps/avl-tree-test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avl-tree-test.o.dir/build.make CMakeFiles/avl-tree-test.o.dir/src/main-apps/avl-tree-test.cpp.i
.PHONY : src/main-apps/avl-tree-test.cpp.i

src/main-apps/avl-tree-test.s: src/main-apps/avl-tree-test.cpp.s
.PHONY : src/main-apps/avl-tree-test.s

# target to generate assembly for a file
src/main-apps/avl-tree-test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avl-tree-test.o.dir/build.make CMakeFiles/avl-tree-test.o.dir/src/main-apps/avl-tree-test.cpp.s
.PHONY : src/main-apps/avl-tree-test.cpp.s

src/main-apps/calculator.o: src/main-apps/calculator.cpp.o
.PHONY : src/main-apps/calculator.o

# target to build an object file
src/main-apps/calculator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.o.dir/build.make CMakeFiles/calculator.o.dir/src/main-apps/calculator.cpp.o
.PHONY : src/main-apps/calculator.cpp.o

src/main-apps/calculator.i: src/main-apps/calculator.cpp.i
.PHONY : src/main-apps/calculator.i

# target to preprocess a source file
src/main-apps/calculator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.o.dir/build.make CMakeFiles/calculator.o.dir/src/main-apps/calculator.cpp.i
.PHONY : src/main-apps/calculator.cpp.i

src/main-apps/calculator.s: src/main-apps/calculator.cpp.s
.PHONY : src/main-apps/calculator.s

# target to generate assembly for a file
src/main-apps/calculator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.o.dir/build.make CMakeFiles/calculator.o.dir/src/main-apps/calculator.cpp.s
.PHONY : src/main-apps/calculator.cpp.s

src/main-apps/magic-square.o: src/main-apps/magic-square.cpp.o
.PHONY : src/main-apps/magic-square.o

# target to build an object file
src/main-apps/magic-square.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magic-square.o.dir/build.make CMakeFiles/magic-square.o.dir/src/main-apps/magic-square.cpp.o
.PHONY : src/main-apps/magic-square.cpp.o

src/main-apps/magic-square.i: src/main-apps/magic-square.cpp.i
.PHONY : src/main-apps/magic-square.i

# target to preprocess a source file
src/main-apps/magic-square.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magic-square.o.dir/build.make CMakeFiles/magic-square.o.dir/src/main-apps/magic-square.cpp.i
.PHONY : src/main-apps/magic-square.cpp.i

src/main-apps/magic-square.s: src/main-apps/magic-square.cpp.s
.PHONY : src/main-apps/magic-square.s

# target to generate assembly for a file
src/main-apps/magic-square.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magic-square.o.dir/build.make CMakeFiles/magic-square.o.dir/src/main-apps/magic-square.cpp.s
.PHONY : src/main-apps/magic-square.cpp.s

src/main-apps/strassen-matrix-mult.o: src/main-apps/strassen-matrix-mult.cpp.o
.PHONY : src/main-apps/strassen-matrix-mult.o

# target to build an object file
src/main-apps/strassen-matrix-mult.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strassen-matrix-mult.o.dir/build.make CMakeFiles/strassen-matrix-mult.o.dir/src/main-apps/strassen-matrix-mult.cpp.o
.PHONY : src/main-apps/strassen-matrix-mult.cpp.o

src/main-apps/strassen-matrix-mult.i: src/main-apps/strassen-matrix-mult.cpp.i
.PHONY : src/main-apps/strassen-matrix-mult.i

# target to preprocess a source file
src/main-apps/strassen-matrix-mult.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strassen-matrix-mult.o.dir/build.make CMakeFiles/strassen-matrix-mult.o.dir/src/main-apps/strassen-matrix-mult.cpp.i
.PHONY : src/main-apps/strassen-matrix-mult.cpp.i

src/main-apps/strassen-matrix-mult.s: src/main-apps/strassen-matrix-mult.cpp.s
.PHONY : src/main-apps/strassen-matrix-mult.s

# target to generate assembly for a file
src/main-apps/strassen-matrix-mult.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strassen-matrix-mult.o.dir/build.make CMakeFiles/strassen-matrix-mult.o.dir/src/main-apps/strassen-matrix-mult.cpp.s
.PHONY : src/main-apps/strassen-matrix-mult.cpp.s

src/max-heap-test.o: src/max-heap-test.cpp.o
.PHONY : src/max-heap-test.o

# target to build an object file
src/max-heap-test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/max-heap-test.o.dir/build.make CMakeFiles/max-heap-test.o.dir/src/max-heap-test.cpp.o
.PHONY : src/max-heap-test.cpp.o

src/max-heap-test.i: src/max-heap-test.cpp.i
.PHONY : src/max-heap-test.i

# target to preprocess a source file
src/max-heap-test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/max-heap-test.o.dir/build.make CMakeFiles/max-heap-test.o.dir/src/max-heap-test.cpp.i
.PHONY : src/max-heap-test.cpp.i

src/max-heap-test.s: src/max-heap-test.cpp.s
.PHONY : src/max-heap-test.s

# target to generate assembly for a file
src/max-heap-test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/max-heap-test.o.dir/build.make CMakeFiles/max-heap-test.o.dir/src/max-heap-test.cpp.s
.PHONY : src/max-heap-test.cpp.s

src/min-heap-test.o: src/min-heap-test.cpp.o
.PHONY : src/min-heap-test.o

# target to build an object file
src/min-heap-test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min-heap-test.o.dir/build.make CMakeFiles/min-heap-test.o.dir/src/min-heap-test.cpp.o
.PHONY : src/min-heap-test.cpp.o

src/min-heap-test.i: src/min-heap-test.cpp.i
.PHONY : src/min-heap-test.i

# target to preprocess a source file
src/min-heap-test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min-heap-test.o.dir/build.make CMakeFiles/min-heap-test.o.dir/src/min-heap-test.cpp.i
.PHONY : src/min-heap-test.cpp.i

src/min-heap-test.s: src/min-heap-test.cpp.s
.PHONY : src/min-heap-test.s

# target to generate assembly for a file
src/min-heap-test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min-heap-test.o.dir/build.make CMakeFiles/min-heap-test.o.dir/src/min-heap-test.cpp.s
.PHONY : src/min-heap-test.cpp.s

src/prefix-to-postfix.o: src/prefix-to-postfix.cpp.o
.PHONY : src/prefix-to-postfix.o

# target to build an object file
src/prefix-to-postfix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prefix-to-postfix.o.dir/build.make CMakeFiles/prefix-to-postfix.o.dir/src/prefix-to-postfix.cpp.o
.PHONY : src/prefix-to-postfix.cpp.o

src/prefix-to-postfix.i: src/prefix-to-postfix.cpp.i
.PHONY : src/prefix-to-postfix.i

# target to preprocess a source file
src/prefix-to-postfix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prefix-to-postfix.o.dir/build.make CMakeFiles/prefix-to-postfix.o.dir/src/prefix-to-postfix.cpp.i
.PHONY : src/prefix-to-postfix.cpp.i

src/prefix-to-postfix.s: src/prefix-to-postfix.cpp.s
.PHONY : src/prefix-to-postfix.s

# target to generate assembly for a file
src/prefix-to-postfix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prefix-to-postfix.o.dir/build.make CMakeFiles/prefix-to-postfix.o.dir/src/prefix-to-postfix.cpp.s
.PHONY : src/prefix-to-postfix.cpp.s

src/search-algorithms/binary-search.o: src/search-algorithms/binary-search.cpp.o
.PHONY : src/search-algorithms/binary-search.o

# target to build an object file
src/search-algorithms/binary-search.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary-search.o.dir/build.make CMakeFiles/binary-search.o.dir/src/search-algorithms/binary-search.cpp.o
.PHONY : src/search-algorithms/binary-search.cpp.o

src/search-algorithms/binary-search.i: src/search-algorithms/binary-search.cpp.i
.PHONY : src/search-algorithms/binary-search.i

# target to preprocess a source file
src/search-algorithms/binary-search.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary-search.o.dir/build.make CMakeFiles/binary-search.o.dir/src/search-algorithms/binary-search.cpp.i
.PHONY : src/search-algorithms/binary-search.cpp.i

src/search-algorithms/binary-search.s: src/search-algorithms/binary-search.cpp.s
.PHONY : src/search-algorithms/binary-search.s

# target to generate assembly for a file
src/search-algorithms/binary-search.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary-search.o.dir/build.make CMakeFiles/binary-search.o.dir/src/search-algorithms/binary-search.cpp.s
.PHONY : src/search-algorithms/binary-search.cpp.s

src/search-algorithms/linear-search.o: src/search-algorithms/linear-search.cpp.o
.PHONY : src/search-algorithms/linear-search.o

# target to build an object file
src/search-algorithms/linear-search.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linear-search.o.dir/build.make CMakeFiles/linear-search.o.dir/src/search-algorithms/linear-search.cpp.o
.PHONY : src/search-algorithms/linear-search.cpp.o

src/search-algorithms/linear-search.i: src/search-algorithms/linear-search.cpp.i
.PHONY : src/search-algorithms/linear-search.i

# target to preprocess a source file
src/search-algorithms/linear-search.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linear-search.o.dir/build.make CMakeFiles/linear-search.o.dir/src/search-algorithms/linear-search.cpp.i
.PHONY : src/search-algorithms/linear-search.cpp.i

src/search-algorithms/linear-search.s: src/search-algorithms/linear-search.cpp.s
.PHONY : src/search-algorithms/linear-search.s

# target to generate assembly for a file
src/search-algorithms/linear-search.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linear-search.o.dir/build.make CMakeFiles/linear-search.o.dir/src/search-algorithms/linear-search.cpp.s
.PHONY : src/search-algorithms/linear-search.cpp.s

src/search-algorithms/recursive-binary-search.o: src/search-algorithms/recursive-binary-search.cpp.o
.PHONY : src/search-algorithms/recursive-binary-search.o

# target to build an object file
src/search-algorithms/recursive-binary-search.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/recursive-binary-search.o.dir/build.make CMakeFiles/recursive-binary-search.o.dir/src/search-algorithms/recursive-binary-search.cpp.o
.PHONY : src/search-algorithms/recursive-binary-search.cpp.o

src/search-algorithms/recursive-binary-search.i: src/search-algorithms/recursive-binary-search.cpp.i
.PHONY : src/search-algorithms/recursive-binary-search.i

# target to preprocess a source file
src/search-algorithms/recursive-binary-search.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/recursive-binary-search.o.dir/build.make CMakeFiles/recursive-binary-search.o.dir/src/search-algorithms/recursive-binary-search.cpp.i
.PHONY : src/search-algorithms/recursive-binary-search.cpp.i

src/search-algorithms/recursive-binary-search.s: src/search-algorithms/recursive-binary-search.cpp.s
.PHONY : src/search-algorithms/recursive-binary-search.s

# target to generate assembly for a file
src/search-algorithms/recursive-binary-search.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/recursive-binary-search.o.dir/build.make CMakeFiles/recursive-binary-search.o.dir/src/search-algorithms/recursive-binary-search.cpp.s
.PHONY : src/search-algorithms/recursive-binary-search.cpp.s

src/sort-algorithms/bubble-sort.o: src/sort-algorithms/bubble-sort.cpp.o
.PHONY : src/sort-algorithms/bubble-sort.o

# target to build an object file
src/sort-algorithms/bubble-sort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bubble-sort.o.dir/build.make CMakeFiles/bubble-sort.o.dir/src/sort-algorithms/bubble-sort.cpp.o
.PHONY : src/sort-algorithms/bubble-sort.cpp.o

src/sort-algorithms/bubble-sort.i: src/sort-algorithms/bubble-sort.cpp.i
.PHONY : src/sort-algorithms/bubble-sort.i

# target to preprocess a source file
src/sort-algorithms/bubble-sort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bubble-sort.o.dir/build.make CMakeFiles/bubble-sort.o.dir/src/sort-algorithms/bubble-sort.cpp.i
.PHONY : src/sort-algorithms/bubble-sort.cpp.i

src/sort-algorithms/bubble-sort.s: src/sort-algorithms/bubble-sort.cpp.s
.PHONY : src/sort-algorithms/bubble-sort.s

# target to generate assembly for a file
src/sort-algorithms/bubble-sort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bubble-sort.o.dir/build.make CMakeFiles/bubble-sort.o.dir/src/sort-algorithms/bubble-sort.cpp.s
.PHONY : src/sort-algorithms/bubble-sort.cpp.s

src/sort-algorithms/merge-sort.o: src/sort-algorithms/merge-sort.cpp.o
.PHONY : src/sort-algorithms/merge-sort.o

# target to build an object file
src/sort-algorithms/merge-sort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/merge-sort.o.dir/build.make CMakeFiles/merge-sort.o.dir/src/sort-algorithms/merge-sort.cpp.o
.PHONY : src/sort-algorithms/merge-sort.cpp.o

src/sort-algorithms/merge-sort.i: src/sort-algorithms/merge-sort.cpp.i
.PHONY : src/sort-algorithms/merge-sort.i

# target to preprocess a source file
src/sort-algorithms/merge-sort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/merge-sort.o.dir/build.make CMakeFiles/merge-sort.o.dir/src/sort-algorithms/merge-sort.cpp.i
.PHONY : src/sort-algorithms/merge-sort.cpp.i

src/sort-algorithms/merge-sort.s: src/sort-algorithms/merge-sort.cpp.s
.PHONY : src/sort-algorithms/merge-sort.s

# target to generate assembly for a file
src/sort-algorithms/merge-sort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/merge-sort.o.dir/build.make CMakeFiles/merge-sort.o.dir/src/sort-algorithms/merge-sort.cpp.s
.PHONY : src/sort-algorithms/merge-sort.cpp.s

src/sort-algorithms/quick-sort.o: src/sort-algorithms/quick-sort.cpp.o
.PHONY : src/sort-algorithms/quick-sort.o

# target to build an object file
src/sort-algorithms/quick-sort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quick-sort.o.dir/build.make CMakeFiles/quick-sort.o.dir/src/sort-algorithms/quick-sort.cpp.o
.PHONY : src/sort-algorithms/quick-sort.cpp.o

src/sort-algorithms/quick-sort.i: src/sort-algorithms/quick-sort.cpp.i
.PHONY : src/sort-algorithms/quick-sort.i

# target to preprocess a source file
src/sort-algorithms/quick-sort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quick-sort.o.dir/build.make CMakeFiles/quick-sort.o.dir/src/sort-algorithms/quick-sort.cpp.i
.PHONY : src/sort-algorithms/quick-sort.cpp.i

src/sort-algorithms/quick-sort.s: src/sort-algorithms/quick-sort.cpp.s
.PHONY : src/sort-algorithms/quick-sort.s

# target to generate assembly for a file
src/sort-algorithms/quick-sort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quick-sort.o.dir/build.make CMakeFiles/quick-sort.o.dir/src/sort-algorithms/quick-sort.cpp.s
.PHONY : src/sort-algorithms/quick-sort.cpp.s

src/sort-algorithms/selection-sort.o: src/sort-algorithms/selection-sort.cpp.o
.PHONY : src/sort-algorithms/selection-sort.o

# target to build an object file
src/sort-algorithms/selection-sort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/selection-sort.o.dir/build.make CMakeFiles/selection-sort.o.dir/src/sort-algorithms/selection-sort.cpp.o
.PHONY : src/sort-algorithms/selection-sort.cpp.o

src/sort-algorithms/selection-sort.i: src/sort-algorithms/selection-sort.cpp.i
.PHONY : src/sort-algorithms/selection-sort.i

# target to preprocess a source file
src/sort-algorithms/selection-sort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/selection-sort.o.dir/build.make CMakeFiles/selection-sort.o.dir/src/sort-algorithms/selection-sort.cpp.i
.PHONY : src/sort-algorithms/selection-sort.cpp.i

src/sort-algorithms/selection-sort.s: src/sort-algorithms/selection-sort.cpp.s
.PHONY : src/sort-algorithms/selection-sort.s

# target to generate assembly for a file
src/sort-algorithms/selection-sort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/selection-sort.o.dir/build.make CMakeFiles/selection-sort.o.dir/src/sort-algorithms/selection-sort.cpp.s
.PHONY : src/sort-algorithms/selection-sort.cpp.s

src/stack-sequence-validation.o: src/stack-sequence-validation.cpp.o
.PHONY : src/stack-sequence-validation.o

# target to build an object file
src/stack-sequence-validation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stack-sequence-validation.o.dir/build.make CMakeFiles/stack-sequence-validation.o.dir/src/stack-sequence-validation.cpp.o
.PHONY : src/stack-sequence-validation.cpp.o

src/stack-sequence-validation.i: src/stack-sequence-validation.cpp.i
.PHONY : src/stack-sequence-validation.i

# target to preprocess a source file
src/stack-sequence-validation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stack-sequence-validation.o.dir/build.make CMakeFiles/stack-sequence-validation.o.dir/src/stack-sequence-validation.cpp.i
.PHONY : src/stack-sequence-validation.cpp.i

src/stack-sequence-validation.s: src/stack-sequence-validation.cpp.s
.PHONY : src/stack-sequence-validation.s

# target to generate assembly for a file
src/stack-sequence-validation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stack-sequence-validation.o.dir/build.make CMakeFiles/stack-sequence-validation.o.dir/src/stack-sequence-validation.cpp.s
.PHONY : src/stack-sequence-validation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... avl-tree-test.o"
	@echo "... binary-search.o"
	@echo "... binary-tree-test.o"
	@echo "... bubble-sort.o"
	@echo "... calculator.o"
	@echo "... cd-linked-list-test.o"
	@echo "... check-expression-balance.o"
	@echo "... decimal-number-calc.o"
	@echo "... evaluate-infix.o"
	@echo "... kmp-pattern-matching.o"
	@echo "... linear-search.o"
	@echo "... linked-list-test.o"
	@echo "... magic-square.o"
	@echo "... max-heap-test.o"
	@echo "... merge-sort.o"
	@echo "... min-heap-test.o"
	@echo "... prefix-to-postfix.o"
	@echo "... quick-sort.o"
	@echo "... recursive-binary-search.o"
	@echo "... selection-sort.o"
	@echo "... stack-sequence-validation.o"
	@echo "... strassen-matrix-mult.o"
	@echo "... src/AVLTree/AVLTree.o"
	@echo "... src/AVLTree/AVLTree.i"
	@echo "... src/AVLTree/AVLTree.s"
	@echo "... src/BinaryTree/BinaryTree.o"
	@echo "... src/BinaryTree/BinaryTree.i"
	@echo "... src/BinaryTree/BinaryTree.s"
	@echo "... src/CDLinkedList/CDLinkedList.o"
	@echo "... src/CDLinkedList/CDLinkedList.i"
	@echo "... src/CDLinkedList/CDLinkedList.s"
	@echo "... src/DecimalNumber/DecimalNumber.o"
	@echo "... src/DecimalNumber/DecimalNumber.i"
	@echo "... src/DecimalNumber/DecimalNumber.s"
	@echo "... src/Heap/MaxHeap.o"
	@echo "... src/Heap/MaxHeap.i"
	@echo "... src/Heap/MaxHeap.s"
	@echo "... src/Heap/MinHeap.o"
	@echo "... src/Heap/MinHeap.i"
	@echo "... src/Heap/MinHeap.s"
	@echo "... src/LinkedList/LinkedList.o"
	@echo "... src/LinkedList/LinkedList.i"
	@echo "... src/LinkedList/LinkedList.s"
	@echo "... src/Queue/Queue.o"
	@echo "... src/Queue/Queue.i"
	@echo "... src/Queue/Queue.s"
	@echo "... src/Stack/Stack.o"
	@echo "... src/Stack/Stack.i"
	@echo "... src/Stack/Stack.s"
	@echo "... src/binary-tree-test.o"
	@echo "... src/binary-tree-test.i"
	@echo "... src/binary-tree-test.s"
	@echo "... src/cd-linked-list-test.o"
	@echo "... src/cd-linked-list-test.i"
	@echo "... src/cd-linked-list-test.s"
	@echo "... src/check-expression-balance.o"
	@echo "... src/check-expression-balance.i"
	@echo "... src/check-expression-balance.s"
	@echo "... src/decimal-number-calc.o"
	@echo "... src/decimal-number-calc.i"
	@echo "... src/decimal-number-calc.s"
	@echo "... src/evaluate-infix.o"
	@echo "... src/evaluate-infix.i"
	@echo "... src/evaluate-infix.s"
	@echo "... src/kmp-pattern-matching.o"
	@echo "... src/kmp-pattern-matching.i"
	@echo "... src/kmp-pattern-matching.s"
	@echo "... src/linked-list-test.o"
	@echo "... src/linked-list-test.i"
	@echo "... src/linked-list-test.s"
	@echo "... src/main-apps/avl-tree-test.o"
	@echo "... src/main-apps/avl-tree-test.i"
	@echo "... src/main-apps/avl-tree-test.s"
	@echo "... src/main-apps/calculator.o"
	@echo "... src/main-apps/calculator.i"
	@echo "... src/main-apps/calculator.s"
	@echo "... src/main-apps/magic-square.o"
	@echo "... src/main-apps/magic-square.i"
	@echo "... src/main-apps/magic-square.s"
	@echo "... src/main-apps/strassen-matrix-mult.o"
	@echo "... src/main-apps/strassen-matrix-mult.i"
	@echo "... src/main-apps/strassen-matrix-mult.s"
	@echo "... src/max-heap-test.o"
	@echo "... src/max-heap-test.i"
	@echo "... src/max-heap-test.s"
	@echo "... src/min-heap-test.o"
	@echo "... src/min-heap-test.i"
	@echo "... src/min-heap-test.s"
	@echo "... src/prefix-to-postfix.o"
	@echo "... src/prefix-to-postfix.i"
	@echo "... src/prefix-to-postfix.s"
	@echo "... src/search-algorithms/binary-search.o"
	@echo "... src/search-algorithms/binary-search.i"
	@echo "... src/search-algorithms/binary-search.s"
	@echo "... src/search-algorithms/linear-search.o"
	@echo "... src/search-algorithms/linear-search.i"
	@echo "... src/search-algorithms/linear-search.s"
	@echo "... src/search-algorithms/recursive-binary-search.o"
	@echo "... src/search-algorithms/recursive-binary-search.i"
	@echo "... src/search-algorithms/recursive-binary-search.s"
	@echo "... src/sort-algorithms/bubble-sort.o"
	@echo "... src/sort-algorithms/bubble-sort.i"
	@echo "... src/sort-algorithms/bubble-sort.s"
	@echo "... src/sort-algorithms/merge-sort.o"
	@echo "... src/sort-algorithms/merge-sort.i"
	@echo "... src/sort-algorithms/merge-sort.s"
	@echo "... src/sort-algorithms/quick-sort.o"
	@echo "... src/sort-algorithms/quick-sort.i"
	@echo "... src/sort-algorithms/quick-sort.s"
	@echo "... src/sort-algorithms/selection-sort.o"
	@echo "... src/sort-algorithms/selection-sort.i"
	@echo "... src/sort-algorithms/selection-sort.s"
	@echo "... src/stack-sequence-validation.o"
	@echo "... src/stack-sequence-validation.i"
	@echo "... src/stack-sequence-validation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

